---
  - name: Create Azure VM
    hosts: localhost
    connection: local
    tasks:
    - name: Delete VMs
      azure_rm_virtualmachine:
        state: absent
        resource_group: "{{ resource_group }}"
        name: "{{ item.name }}"
      loop: "{{ azure_vms }}"
    - name: Delete virtual network inteface cards
      azure_rm_networkinterface:
        state: absent
        resource_group: "{{ resource_group }}"
        name: "{{ item.name }}network"
        virtual_network: "automation_testing-vnet"
      loop: "{{ azure_vms }}"
    - name: Delete load balancer
      azure_rm_loadbalancer:
        state: absent
        resource_group: "{{ resource_group }}"
        name: DevLB
    - name: Delete public ip
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        name: "{{ public_ip_name }}"
        state: absent
    - name: Delete storage accounts
      azure_rm_storageaccount:
        state: absent
        force_delete_nonempty: yes
        resource_group: "{{ resource_group }}"
        name: "{{ item.name }}storage"
      loop: "{{ azure_vms }}"
    - name: Delete Network Security Group
      azure_rm_securitygroup:
        state: absent
        resource_group: "{{ resource_group }}"
        name: "test_nsg"
    - name: Delete a availability set
      azure_rm_availabilityset:
        state: absent
        name: "{{ availability_set }}"
        location: "{{ location }}"
        resource_group: "{{ resource_group }}"
...
