---
  - name: Create Azure VM
    hosts: localhost
    connection: local
    vars:
      resource_group: "AUTOMATION_TESTING"
      vm_name: testvm
      location: eastus
      availability_set: "LyasAvailabilitySet"
      ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDHcXUqYnlL4bd4jxx8TQ9xJ0Cdj1omNQinUvcsI6OvpHQua0oKt9elxq2nQJLW1p+69L0U58GuTrpFAT3JFbdKn5y+sNO9eyI33Ylyu/YwXZJtcFaW/7WxcxV11qeEddXi19dqA77bDkWesco3hqEYeIW1LmvluE9BH/diLZZviSAhGcYi/AfB1uvGT6ATjM++dJ7YzGDSx/8yVXDwWzgqEI7p9keTktzwRLgH13RjSmOKMiOBT1rdR5k5yYtnLxSYCgpnUKyUfP5k522YWza+5IS8CffcKHseb6+kbB8i4Hvz0DAA+JM3vkLqMh0KIvuufPd/oPuXPu8+egbsAR8fEXFiK9OUxGCysMWoNiOIDVp7INDJOhpfSAevPDIMWTi5qbIIjPooDyhBHpoekucpmJ5ODBv0pK+4Z9vJT89Y4J2lCR/ZQOWc9YiHJJGQ0q//qo8LPUy8YQ0/IJSaewX0F0arPQfIjRo09CVR1oFJqxPh5TWKbVXvAPn13a99XD8="
    tasks:
    - name: Delete VMs
      azure_rm_virtualmachine:
        state: absent
        resource_group: "{{ resource_group }}"
        name: "{{ item.name }}"
      loop: "{{ azure_vms }}"
    - name: Delete virtual network inteface cards
      azure_rm_networkinterface:
        state: absent
        resource_group: "{{ resource_group }}"
        name: "{{ item.name }}network"
        virtual_network: "automation_testing-vnet"
      loop: "{{ azure_vms }}"
    - name: Delete load balancer
      azure_rm_loadbalancer:
        state: absent
        resource_group: "{{ resource_group }}"
        name: DevLB
    - name: Delete storage accounts
      azure_rm_storageaccount:
        state: absent
        force_delete_nonempty: yes
        resource_group: "{{ resource_group }}"
        name: "{{ item.name }}storage"
      loop: "{{ azure_vms }}"
    - name: Delete Network Security Group
      azure_rm_securitygroup:
        state: absent
        resource_group: "{{ resource_group }}"
        name: "test_nsg"
    - name: Delete a availability set
      azure_rm_availabilityset:
        state: absent
        name: "{{ availability_set }}"
        location: "{{ location }}"
        resource_group: "{{ resource_group }}"
...
